
import { Translations } from './types';

export const TRANSLATIONS: Translations = {
  appName: { en: "OD Calculate It Right", ar: "OD احسبها صح" },
  home: { en: "Home", ar: "الرئيسية" },
  loanCalc: { en: "Loan Calculator", ar: "حاسبة القروض" },
  billSplit: { en: "Bill Splitter", ar: "تقسيم الفاتورة" },
  budget: { en: "Budget Tracker", ar: "مراقب الميزانية" },
  savings: { en: "Savings Planner", ar: "مخطط الادخار" },
  reports: { en: "Reports", ar: "التقارير" },
  generalCalc: { en: "General Calculations", ar: "الحسابات العامة" },
  about: { en: "About Us", ar: "من نحن" },
  settings: { en: "Settings", ar: "الإعدادات" },
  tagline: { en: "Smart Financial Decisions", ar: "قرارات مالية ذكية" },
  calculate: { en: "Calculate", ar: "احسب" },
  price: { en: "Original Price", ar: "السعر الأصلي" },
  downPayment: { en: "Down Payment", ar: "الدفعة الأولى" },
  monthlyInstallment: { en: "Monthly Installment", ar: "القسط الشهري" },
  months: { en: "Number of Months", ar: "عدد الأشهر" },
  totalPaid: { en: "Total Amount Paid", ar: "إجمالي المبلغ المدفوع" },
  interest: { en: "Total Interest", ar: "إجمالي الفائدة" },
  dealStatus: { en: "Deal Evaluation", ar: "تقييم الصفقة" },
  good: { en: "Good Deal", ar: "صفقة جيدة" },
  acceptable: { en: "Acceptable", ar: "صفقة مقبولة" },
  overpriced: { en: "Overpriced", ar: "سعر مبالغ فيه" },
  billTotal: { en: "Total Bill Amount", ar: "إجمالي الفاتورة" },
  numPeople: { en: "Number of People", ar: "عدد الأشخاص" },
  eachPays: { en: "Each Person Pays", ar: "نصيب الفرد" },
  owes: { en: "owes", ar: "يدين لـ" },
  language: { en: "Language", ar: "اللغة" },
  theme: { en: "Theme", ar: "المظهر" },
  currency: { en: "Currency Symbol", ar: "رمز العملة" },
  dark: { en: "Dark", ar: "داكن" },
  light: { en: "Light", ar: "فاتح" },
  goodThreshold: { en: "Good Deal Threshold (%)", ar: "حد الصفقة الجيدة (%)" },
  thresholdDesc: { en: "Determine at what interest rate a deal is no longer 'Good'.", ar: "حدد معدل الفائدة الذي بعده لا تعتبر الصفقة 'جيدة'." },
  income: { en: "Income", ar: "الدخل" },
  expenses: { en: "Expenses", ar: "المصاريف" },
  limit: { en: "Monthly Limit", ar: "الحد الشهري" },
  food: { en: "Food", ar: "طعام" },
  transport: { en: "Transport", ar: "مواصلات" },
  shopping: { en: "Shopping", ar: "تسوق" },
  bills: { en: "Bills", ar: "فواتير" },
  other: { en: "Other", ar: "أخرى" },
  goalName: { en: "Goal Name", ar: "اسم الهدف" },
  targetAmount: { en: "Target Amount", ar: "المبلغ المستهدف" },
  savedSoFar: { en: "Saved So Far", ar: "تم توفيره" },
  weeklyNeed: { en: "Weekly Saving Required", ar: "الادخار الأسبوعي المطلوب" },
  insightText: { en: "Insights", ar: "رؤى ذكية" },
  tipOfDay: { en: "Tip of the Day", ar: "نصيحة اليوم" },
  welcome: { en: "Welcome", ar: "أهلاً بك" },
  getStarted: { en: "Start App", ar: "ابدأ التطبيق" },
  onboarding1: { en: "Loan Calculator: Evaluate your financial deals instantly.", ar: "حاسبة القروض: قيم صفقاتك المالية فوراً." },
  onboarding2: { en: "Bill Splitter: Divide costs fairly with your friends.", ar: "تقسيم الفاتورة: قسم التكاليف بعدل مع أصدقائك." },
  onboarding3: { en: "Budget Tracker: Monitor your daily spending and income.", ar: "مراقب الميزانية: راقب نفقاتك اليومية ودخلك." },
  onboarding4: { en: "Savings Planner: Reach your financial goals faster.", ar: "مخطط الادخار: حقق أهدافك المالية بشكل أسرع." },
  placeholderPrice: { en: "Enter original price", ar: "أدخل السعر الأصلي" },
  placeholderDown: { en: "Enter down payment", ar: "أدخل الدفعة الأولى" },
  placeholderInstallment: { en: "Enter monthly payment", ar: "أدخل القسط الشهري" },
  placeholderMonths: { en: "Enter number of months", ar: "أدخل عدد الأشهر" },
  chooseLang: { en: "Choose Language", ar: "اختر اللغة" },
  chooseCurrency: { en: "Choose Currency", ar: "اختر العملة" },
  aboutDesc: { 
    en: "OD Calculate It Right is a high-performance productivity tool by Oday Qutqut. Designed for precision in loans, bill splitting, and personal finance tracking.",
    ar: "OD احسبها صح هي أداة إنتاجية عالية الأداء من عدي قطقط. مصممة للدقة في القروض وتقسيم الفواتير وتتبع التمويل الشخصي."
  },
  badgeMaster: { en: "Master Splitter", ar: "خبير التقسيم" },
  badgeMasterDesc: { en: "Fairly splitting a large group bill like a pro!", ar: "تقسيم فاتورة مجموعة كبيرة بعدل مثل المحترفين!" },
  perfectSplit: { en: "Perfect Fairness!", ar: "عدالة مطلقة!" },
  
  // General Calculations Translations
  commTitle: { en: "Sales Commission", ar: "عمولة بيع" },
  tradeTitle: { en: "Trade Profit", ar: "أرباح تجارة" },
  constTitle: { en: "Construction Cost", ar: "تكاليف بناء" },
  goldTitle: { en: "Gold Value", ar: "قيمة الذهب" },
  
  saleAmount: { en: "Sale Amount", ar: "قيمة المبيعات" },
  commRate: { en: "Commission Rate (%)", ar: "نسبة العمولة (%)" },
  commVal: { en: "Commission Value", ar: "قيمة العمولة" },
  
  buyPrice: { en: "Purchase Price", ar: "سعر الشراء" },
  sellPrice: { en: "Selling Price", ar: "سعر البيع" },
  otherCosts: { en: "Other Costs (Fees, Shipping)", ar: "تكاليف أخرى (رسوم، شحن)" },
  netProfit: { en: "Net Profit", ar: "صافي الربح" },
  margin: { en: "Profit Margin", ar: "هامش الربح" },
  
  matQty: { en: "Material Quantity", ar: "كمية المواد" },
  unitPrice: { en: "Unit Price", ar: "سعر الوحدة" },
  laborCost: { en: "Labor Cost", ar: "تكلفة العمالة" },
  totalConst: { en: "Total Construction Cost", ar: "إجمالي تكاليف البناء" },
  breakdown: { en: "Breakdown", ar: "التفصيل" },
  
  goldWeight: { en: "Gold Weight (Grams)", ar: "وزن الذهب (جرام)" },
  goldPriceG: { en: "Gold Price per Gram", ar: "سعر الذهب للجرام" },
  additionalFees: { en: "Additional Fees / Design", ar: "مصنعية / رسوم إضافية" },
  totalGoldVal: { en: "Total Gold Value", ar: "إجمالي قيمة الذهب" },

  placeholderSale: { en: "Enter sale amount", ar: "أدخل قيمة البيع" },
  placeholderRate: { en: "Enter rate %", ar: "أدخل النسبة" },
  placeholderBuy: { en: "Enter purchase price", ar: "أدخل سعر الشراء" },
  placeholderSell: { en: "Enter selling price", ar: "أدخل سعر البيع" },
  placeholderOther: { en: "Enter other costs", ar: "أدخل التكاليف الأخرى" },
  placeholderQty: { en: "Enter quantity", ar: "أدخل الكمية" },
  placeholderUnit: { en: "Enter unit price", ar: "أدخل سعر الوحدة" },
  placeholderLabor: { en: "Enter labor costs", ar: "أدخل تكلفة العمالة" },
  placeholderWeight: { en: "Enter gold weight", ar: "أدخل وزن الذهب" },
  placeholderGoldPrice: { en: "Enter price per gram", ar: "أدخل سعر الجرام" },
  placeholderFees: { en: "Enter fees", ar: "أدخل الرسوم" }
};

export const TIPS = [
  { en: "Try to save at least 20% of your income every month.", ar: "حاول ادخار 20٪ على الأقل من دخلك كل شهر." },
  { en: "Always compare loan interest rates before signing.", ar: "قارن دائماً بين أسعار فائدة القروض قبل التوقيع." },
  { en: "Track even the small expenses; they add up fast!", ar: "تتبع حتى المصاريف الصغيرة؛ فهي تتراكم بسرعة!" },
  { en: "A 'Good Deal' is one that fits your long-term budget.", ar: "الصفقة الجيدة هي تلك التي تناسب ميزانيتك طويلة المدى." }
];
